### ISSUE TITLE
Fails to compile with GHC7.8

### ISSUE THREAD

**Issue by phadej** [bartavelle/pcre-utils#2]
cabal solver picks `mtl-2.1` which doesn't has `Control.Monad.Except`. Please specify lower and upper bounds to comply with PVP.

See http://matrix.hackage.haskell.org/package/pcre-utils

```
Text/Regex/PCRE/ByteString/Utils.hs:32:8:
    Could not find module ‘Control.Monad.Except’
    Perhaps you meant
      Control.Monad.Cont (from mtl-2.1.3.1)
      Control.Monad.Error (from mtl-2.1.3.1)
      Control.Monad.List (from mtl-2.1.3.1)
    Use -v to see a list of the files searched for.
```

**Comment by bartavelle** [comment]
Just added a quick lower bound to `mtl`. I will try to fix it properly asap.

**Comment by bartavelle** [comment]
Thanks for reporting this by the way!
